// GitHub data layer. Fetched on the server, cached by Next for `revalidate` seconds.
// Set GITHUB_TOKEN in .env.local to raise the rate limit from 60/hr to 5000/hr.

export type Repo = {
  name: string;
  description: string | null;
  html_url: string;
  homepage: string | null;
  language: string | null;
  languages_url?: string;
  techStacks: string[];
  stargazers_count: number;
  forks_count: number;
  topics: string[];
  pushed_at: string;
  fork: boolean;
  archived: boolean;
};

export type Profile = {
  login: string;
  name: string | null;
  bio: string | null;
  avatar_url: string;
  html_url: string;
  location: string | null;
  public_repos: number;
  followers: number;
};

import { GITHUB_CONFIG, CACHE_CONFIG } from "@/lib/constants";
import reposFallback from "@/lib/repos-fallback.json";

function headers(): HeadersInit {
  const h: HeadersInit = {
    Accept: GITHUB_CONFIG.ACCEPT_HEADER,
    "X-GitHub-Api-Version": GITHUB_CONFIG.API_VERSION,
  };
  const token = process.env.GH_TOKEN || process.env.GITHUB_TOKEN;
  if (token) {
    (h as Record<string, string>).Authorization = `Bearer ${token}`;
  }
  return h;
}

// Never let a GitHub outage or a rate-limit take the whole page down.
async function get<T>(path: string, fallback: T): Promise<T> {
  try {
    const url = path.startsWith("http") ? path : `${GITHUB_CONFIG.API_BASE_URL}${path}`;
    const res = await fetch(url, {
      headers: headers(),
      next: { revalidate: CACHE_CONFIG.GITHUB_REVALIDATE_SECONDS },
    });
    if (!res.ok) {
      console.error(`GitHub ${path} -> ${res.status} ${res.statusText}`);
      return fallback;
    }
    return (await res.json()) as T;
  } catch (err) {
    console.error(`GitHub ${path} failed`, err);
    return fallback;
  }
}

export function getProfile(user: string) {
  return get<Profile | null>(`/users/${user}`, null);
}

// Backend-first ordering. Backend work outranks everything; Java breaks ties
// above other languages. Tune by editing these two, not the sort below.
const BACKEND_NAME = /(^|[-_])(api|be|backend|server|rest|crud|service)([-_]|$)/i;
const BACKEND_LANGS = new Set(["Java", "Go", "C#", "Kotlin", "Rust", "Python", "Dart", "Flutter"]);

// Language section order on /projects and hero primary languages.
export const LANG_PRIORITY = [
  "Java",
  "Go",
  "C#",
  "TypeScript",
  "JavaScript",
  "PHP",
  "Python",
  "Flutter",
  "Dart",
];

const FLUTTER_GENERATED_NOISE = new Set(["C++", "CMake", "C", "Objective-C", "HTML"]);

const TOPIC_TECH_MAP: Record<string, string> = {
  "spring-boot": "Spring Boot",
  springboot: "Spring Boot",
  spring: "Spring Boot",
  flutter: "Flutter",
  dart: "Dart",
  react: "React",
  "react-native": "React Native",
  reactjs: "React",
  nextjs: "Next.js",
  "next.js": "Next.js",
  vue: "Vue",
  vuejs: "Vue",
  laravel: "Laravel",
  express: "Express",
  expressjs: "Express",
  nodejs: "Node.js",
  node: "Node.js",
  dotnet: ".NET",
  ".net": ".NET",
  csharp: "C#",
  "c#": "C#",
  golang: "Go",
  go: "Go",
  java: "Java",
  typescript: "TypeScript",
  javascript: "JavaScript",
  php: "PHP",
  tailwindcss: "Tailwind CSS",
  tailwind: "Tailwind CSS",
  postgresql: "PostgreSQL",
  postgres: "PostgreSQL",
  mongodb: "MongoDB",
  mongo: "MongoDB",
  mysql: "MySQL",
  redis: "Redis",
  docker: "Docker",
};

// Heuristic keyword matching on repository names
const NAME_STACK_PATTERNS: Array<[RegExp, string[]]> = [
  [/flutter/i, ["Flutter", "Dart"]],
  [/react/i, ["React", "JavaScript"]],
  [/vue/i, ["Vue", "JavaScript"]],
  [/mern/i, ["MongoDB", "Express", "React", "Node.js"]],
  [/mongo.*node|node.*mongo/i, ["MongoDB", "Node.js", "Express"]],
  [/net[-_]?core|enigpus/i, [".NET", "C#"]],
  [/express/i, ["Node.js", "Express"]],
  [/lara|eshop/i, ["PHP", "Laravel"]],
  [/spring/i, ["Java", "Spring Boot"]],
];

function normalizeTechStacks(
  rawRepo: { name: string; language: string | null; topics: string[]; languages_url?: string },
  langObj: Record<string, number>
): { primaryLang: string | null; stacks: string[] } {
  const isFlutter =
    rawRepo.name.toLowerCase().includes("flutter") ||
    rawRepo.topics.some((t) => t.toLowerCase() === "flutter");

  let langs = Object.keys(langObj);

  // Normalize language names
  langs = langs
    .map((l) => {
      if (l === "Dockerfile") return "Docker";
      if (l === "SCSS") return "CSS";
      if (l === "PLpgSQL") return "PostgreSQL";
      return l;
    })
    .filter((l) => l !== "Procfile");

  if (isFlutter) {
    // Strip out C++/CMake desktop runner boilerplate generated by Flutter CLI
    langs = langs.filter((l) => !FLUTTER_GENERATED_NOISE.has(l));
    if (!langs.includes("Flutter")) langs.unshift("Flutter");
    if (!langs.includes("Dart")) langs.splice(1, 0, "Dart");
  }

  // Include relevant framework / database topics
  for (const t of rawRepo.topics) {
    const mapped = TOPIC_TECH_MAP[t.toLowerCase()];
    if (mapped && !langs.includes(mapped)) {
      langs.push(mapped);
    }
  }

  // Check name heuristics for rich tech stack detection
  for (const [regex, stacks] of NAME_STACK_PATTERNS) {
    if (regex.test(rawRepo.name)) {
      for (const s of stacks) {
        if (!langs.includes(s)) {
          langs.push(s);
        }
      }
    }
  }

  // Fallback to repo.language if still empty
  if (langs.length === 0 && rawRepo.language) {
    langs.push(rawRepo.language);
  }

  const primaryLang = isFlutter
    ? "Flutter"
    : langs[0] ?? rawRepo.language ?? null;

  return {
    primaryLang,
    stacks: Array.from(new Set(langs)),
  };
}

function rank(r: Repo): number {
  const backend =
    BACKEND_NAME.test(r.name) ||
    (r.language !== null && BACKEND_LANGS.has(r.language)) ||
    r.topics.some((t) => BACKEND_NAME.test(t));
  return (backend ? 2 : 0) + (r.language === "Java" ? 1 : 0);
}

export async function getRepos(user: string, hidden: Set<string>): Promise<Repo[]> {
  const rawRepos = await get<Repo[]>(
    `/users/${user}/repos?per_page=${GITHUB_CONFIG.REPOS_PER_PAGE}&sort=${GITHUB_CONFIG.SORT_ORDER}`,
    []
  );

  // If rate-limited or GitHub is down, gracefully use local fallback snapshot
  const sourceRepos: Repo[] =
    rawRepos && rawRepos.length > 0
      ? rawRepos
      : (reposFallback as unknown as Repo[]);

  const filtered = sourceRepos.filter(
    (r) => !r.fork && !r.archived && !hidden.has(r.name)
  );

  // Fetch full languages list in parallel when token is configured, or use fast in-memory inference
  const enrichedRepos: Repo[] = await Promise.all(
    filtered.map(async (r) => {
      let langObj: Record<string, number> = {};
      if ((process.env.GH_TOKEN || process.env.GITHUB_TOKEN) && r.languages_url) {
        langObj = await get<Record<string, number>>(r.languages_url, {});
      }
      const { primaryLang, stacks } = normalizeTechStacks(r, langObj);
      return {
        ...r,
        language: primaryLang,
        techStacks: r.techStacks?.length ? r.techStacks : stacks,
      };
    })
  );

  return enrichedRepos.sort(
    (a, b) =>
      rank(b) - rank(a) ||
      b.stargazers_count - a.stargazers_count ||
      Date.parse(b.pushed_at) - Date.parse(a.pushed_at)
  );
}

// "link-shortener-api" -> "Link Shortener API"
const ACRONYMS = new Set(["api", "ui", "cli", "sdk", "db", "jwt", "sql", "rest"]);

export function titleize(slug: string): string {
  return slug
    .split(/[-_.]+/)
    .filter(Boolean)
    .map((w) =>
      ACRONYMS.has(w.toLowerCase())
        ? w.toUpperCase()
        : w.charAt(0).toUpperCase() + w.slice(1),
    )
    .join(" ");
}

export function formatDate(iso: string): string {
  const d = new Date(iso);
  const month = d.toLocaleString("en-US", { month: "short", timeZone: "UTC" });
  const year = d.getUTCFullYear();
  return `${month} ${year}`;
}
